name: Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:

  build-production:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    name: Node ${{ matrix.node-version }}

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1.4.4
      with:
        node-version: ${{ matrix.node-version }}

    - name: yarn install
      run: yarn install
      env:
        CI: true

    - run: yarn run prod
